name: keyboard
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  provider: ^6.0.4
  flutter_dotenv: ^5.0.2
  json_serializable: ^6.5.4
  flutter_tts: ^3.6.1
  google_sign_in: ^5.4.2
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  google_fonts: ^3.0.1
  emojis: ^0.9.9
  rive: ^0.9.1
  get_it: ^7.2.0
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_cache_interceptor_file_store: ^1.2.1
  path_provider: ^2.0.11
  sqflite: ^2.2.0+3
  path: ^1.8.2
  json_annotation: ^4.7.0
  collection: ^1.16.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio_cache_interceptor_hive_store: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/rive/
    - dotenv