// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6AQmv6NkjzWxjMXf31pB64hv_-vo6WOM',
    appId: '1:703376507167:web:54e10180ee9035d4f1f02a',
    messagingSenderId: '703376507167',
    projectId: 'keyboard-98820',
    authDomain: 'keyboard-98820.firebaseapp.com',
    databaseURL: 'https://keyboard-98820-default-rtdb.firebaseio.com',
    storageBucket: 'keyboard-98820.appspot.com',
    measurementId: 'G-SWKCZRPJHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnwlGqD6zLacw4aEGBWJTS5gTvBy-Ij4w',
    appId: '1:703376507167:android:8096e2f2fbb7e38ef1f02a',
    messagingSenderId: '703376507167',
    projectId: 'keyboard-98820',
    databaseURL: 'https://keyboard-98820-default-rtdb.firebaseio.com',
    storageBucket: 'keyboard-98820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZrTFcIwkB_Ecnx1gunO_5Mz8GUg_UbVc',
    appId: '1:703376507167:ios:518be9f1a3f3920af1f02a',
    messagingSenderId: '703376507167',
    projectId: 'keyboard-98820',
    databaseURL: 'https://keyboard-98820-default-rtdb.firebaseio.com',
    storageBucket: 'keyboard-98820.appspot.com',
    androidClientId: '703376507167-0ljh9t92rqcqaei5bbuct8iinn1f7u38.apps.googleusercontent.com',
    iosClientId: '703376507167-t61ndb3o586kvjsg6kbsi99hu29ca151.apps.googleusercontent.com',
    iosBundleId: 'com.stonfacesoft.keyboards',
  );
}
